helmDefaults:
  kubeContext: k3d-dev
  historyMax: 5
  wait: true
  createNamespace: true
  timeout: 600

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana-community
    url: https://grafana-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: podinfo
    url: https://stefanprodan.github.io/podinfo

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.15.1

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.20.2
    values:
      - values/cert-manager.yaml
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "../../install/kubernetes/hooks/configure-cert-manager.sh"

  - name: metrics-server
    namespace: monitoring
    chart: metrics-server/metrics-server
    version: 3.13.0
    values:
      - values/metrics-server.yaml

  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 84.4.0
    values:
      - values/kube-prometheus-stack.yaml.gotmpl
    needs:
      - cert-manager/cert-manager

  - name: loki
    namespace: loki
    chart: grafana-community/loki
    version: 13.5.0
    values:
      - values/loki.yaml

  - name: alloy
    namespace: loki
    chart: grafana/alloy
    version: 1.8.0
    values:
      - values/alloy.yaml
    needs:
      - loki/loki

  - name: podinfo-backend
    namespace: podinfo
    chart: podinfo/podinfo
    version: 6.11.2
    values:
      - values/podinfo-backend.yaml
    needs:
      - monitoring/prometheus

  - name: podinfo-frontend
    namespace: podinfo
    chart: podinfo/podinfo
    version: 6.11.2
    values:
      - values/podinfo-frontend.yaml.gotmpl
    needs:
      - podinfo/podinfo-backend
      - cert-manager/cert-manager
