---
git_protocol: ssh
editor: vim
prompt: enabled
pager: delta
aliases:
  co: pr checkout
  pc: pr create
  pl: pr list
  pm: pr merge
  prc: >-
    !gh api repos/{owner}/{repo}/pulls/$1/comments --jq '.[] |
    "---\n\(.user.login) on \(.path):\(.line)
    (\(.created_at | split("T")[0]))\n\n\(.diff_hunk | split("\n")[-3:]
    | join("\n"))\n\n> \(.body)\n"'
  ps: pr status
  pv: pr view
  pvw: pr view --web
  il: issue list
  iv: issue view
  ic: issue create
  rl: run list
  rw: run watch
  pra: >-
    !gh api repos/{owner}/{repo}/pulls/$1 --jq "\"PR:
    #\(.number)\nURL: \(.html_url)\nMerged-by:
    \(.merged_by.login)\nMerged-at: \(.merged_at)\"" && gh api
    repos/{owner}/{repo}/pulls/$1/reviews --jq "[.[] |
    select(.state == \"APPROVED\")] | .[] | \"Approved-by:
    \(.user.login) (\(.submitted_at | split(\"T\")[0]))\""
version: "1"
