prometheus:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: mkcert-issuer
    ingressClassName: nginx
    hosts:
      - prometheus.$LOCAL_DOMAIN
    paths:
      - /
    pathType: ImplementationSpecific
    tls:
    - secretName: prometheus-general-tls
      hosts:
      - prometheus.$LOCAL_DOMAIN

grafana:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: mkcert-issuer
    ingressClassName: nginx
    hosts:
      - grafana.$LOCAL_DOMAIN
    paths:
      - /
    pathType: ImplementationSpecific
    tls:
    - secretName: grafana-general-tls
      hosts:
      - grafana.$LOCAL_DOMAIN

alertmanager:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: mkcert-issuer
    ingressClassName: nginx
    hosts:
      - alertmanager.$LOCAL_DOMAIN
    paths:
      - /
    pathType: ImplementationSpecific
    tls:
    - secretName: alertmanager-general-tls
      hosts:
      - alertmanager.$LOCAL_DOMAIN

# prometheus-node-exporter:
#   service:
#     type: NodePort
#     nodePort: 32001
