# Spaceship prompt

# Docker
SPACESHIP_DOCKER_SHOW=false

# Google Cloud
SPACESHIP_GCLOUD_SHOW=false

# Node
SPACESHIP_NODE_SHOW=false

# Kubernetes
SPACESHIP_KUBECTL_SHOW=false
SPACESHIP_KUBECTL_VERSION_SHOW=false

# Python
SPACESHIP_VENV_GENERIC_NAMES=(None)

# Misc
SPACESHIP_BATTERY_THRESHOLD=20
SPACESHIP_JOBS_AMOUNT_THRESHOLD=0
