#!/bin/bash

# Enable 'exit on error'
set -e

# Run pytest if there are Python test files in the tests directory
if [ -e "tests" ] && find tests -name "test_*.py" -o -name "*_test.py" | grep -q .; then
    pytest --quiet --quiet --tb=no --strict --exitfirst --disable-warnings
fi

# Run zunit if there are zunit test files in the tests directory
if [ -e "tests" ] && find tests -name "*.zunit" | grep -q .; then
    zunit
fi

# Run behave if there is a features directory
if [ -e "features" ]; then
    behave --quiet --quiet --no-summary --stop --no-timings --format progress
fi

# Add other pre-push hooks
