---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
networking:
  ipFamily: ipv4
  apiServerAddress: 127.0.0.1
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
  - role: control-plane
    # only allow the ingress controller to run on a specific node(s) matching the label selector
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    # allow the local host to make requests to the Ingress controller over ports 80/443
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
    # mount host docker config with auth credentials for pulling images
    extraMounts:
      - hostPath: $HOME/.docker/config.json
        containerPath: /var/lib/kubelet/config.json
      - hostPath: /etc/ssl/certs/corporate.crt
        containerPath: /usr/local/share/ca-certificates/corporate.crt
  - role: worker
  # mount host docker config with auth credentials for pulling images
    extraMounts:
      - hostPath: $HOME/.docker/config.json
        containerPath: /var/lib/kubelet/config.json
      - hostPath: /etc/ssl/certs/corporate.crt
        containerPath: /usr/local/share/ca-certificates/corporate.crt
  - role: worker
  # mount docker config with auth credentials for pulling images
    extraMounts:
      - hostPath: $HOME/.docker/config.json
        containerPath: /var/lib/kubelet/config.json
      - hostPath: /etc/ssl/certs/corporate.crt
        containerPath: /usr/local/share/ca-certificates/corporate.crt
