---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
networking:
  ipFamily: ipv4
  apiServerAddress: 127.0.0.1
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
  - role: control-plane
    # mount host docker config with auth credentials for pulling images
    extraMounts:
      - hostPath: $HOME/.docker/config.json
        containerPath: /var/lib/kubelet/config.json
  - role: worker
  # mount host docker config with auth credentials for pulling images
    extraMounts:
      - hostPath: $HOME/.docker/config.json
        containerPath: /var/lib/kubelet/config.json
  - role: worker
  # mount host docker config with auth credentials for pulling images
    extraMounts:
      - hostPath: $HOME/.docker/config.json
        containerPath: /var/lib/kubelet/config.json
