---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
networking:
  ipFamily: ipv4
  apiServerAddress: 127.0.0.1
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
  - role: control-plane
    extraMounts:
        # mount docker config with auth credentials for pulling images
      - hostPath: $HOME/.docker/config.json
        containerPath: /var/lib/kubelet/config.json
        # mount CA for validating TLS
      - hostPath: /etc/ssl/certs/corporate.crt
        containerPath: /usr/local/share/ca-certificates/corporate.crt
  - role: worker
    extraMounts:
        # mount docker config with auth credentials for pulling images
      - hostPath: $HOME/.docker/config.json
        containerPath: /var/lib/kubelet/config.json
        # mount CA for validating TLS
      - hostPath: /etc/ssl/certs/corporate.crt
        containerPath: /usr/local/share/ca-certificates/corporate.crt
  - role: worker
    extraMounts:
        # mount docker config with auth credentials for pulling images
      - hostPath: $HOME/.docker/config.json
        containerPath: /var/lib/kubelet/config.json
        # mount CA for validating TLS
      - hostPath: /etc/ssl/certs/corporate.crt
        containerPath: /usr/local/share/ca-certificates/corporate.crt
