prometheus:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: mkcert-issuer
    ingressClassName: nginx
    hosts:
      - prometheus.example
    paths:
      - /
    pathType: ImplementationSpecific
    tls:
    - secretName: prometheus-general-tls
      hosts:
      - prometheus.example

grafana:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: mkcert-issuer
    ingressClassName: nginx
    hosts:
      - grafana.example
    paths:
      - /
    pathType: ImplementationSpecific
    tls:
    - secretName: grafana-general-tls
      hosts:
      - grafana.example

alertmanager:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: mkcert-issuer
    ingressClassName: nginx
    hosts:
      - alertmanager.example
    paths:
      - /
    pathType: ImplementationSpecific
    tls:
    - secretName: alertmanager-general-tls
      hosts:
      - alertmanager.example

# prometheus-node-exporter:
#   service:
#     type: NodePort
#     nodePort: 32001
