prometheus:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: mkcert-issuer
    ingressClassName: nginx
    hosts:
      - prometheus.dev.test
    paths:
      - /
    pathType: ImplementationSpecific

    tls:
    - secretName: prometheus-general-tls
      hosts:
      - prometheus.dev.test

grafana:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: mkcert-issuer
    ingressClassName: nginx
    hosts:
      - grafana.dev.test
    paths:
      - /
    pathType: ImplementationSpecific

    tls:
    - secretName: grafana-general-tls
      hosts:
      - grafana.dev.test

alertmanager:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: mkcert-issuer
    ingressClassName: nginx
    hosts:
      - alertmanager.dev.test
    paths:
      - /
    pathType: ImplementationSpecific

    tls:
    - secretName: alertmanager-general-tls
      hosts:
      - alertmanager.dev.test

# prometheus-node-exporter:
#   service:
#     type: NodePort
#     nodePort: 32001
