apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-resource-quota
spec:
  hard:
    # CPU and memory limits
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi

    # Pod count limits
    pods: "10"

    # Storage limits
    requests.storage: 10Gi
    persistentvolumeclaims: "5"

    # Workload limits
    count/deployments.apps: "5"
    count/statefulsets.apps: "2"
    count/jobs.batch: "5"
    count/cronjobs.batch: "3"
